CREATE DATABASE IF NOT EXISTS db_construct;

CREATE TABLE IF NOT EXISTS users(

	id_user INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	nom VARCHAR(50) NOT NULL,
	prenom VARCHAR(100) NOT NULL,
	numero VARCHAR(50) NOT NULL,
	localite VARCHAR(255) NOT NULL,
	fonction VARCHAR(50) NOT NULL,
	email VARCHAR(255) NOT NULL,
	passwords VARCHAR(255) NOT NULL
)ENGINE = INNODB;

CREATE TABLE IF NOT EXISTS service(

	id_serv INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	nom_serv VARCHAR(255) NOT NULL,
	description VARCHAR(255) NOT NULL,
	lieu VARCHAR(255) NOT NULL,
	photo VARCHAR(255) NOT NULL,
	date_deb VARCHAR(255) NOT NULL,
	date_fin VARCHAR(50) NOT NULL
)ENGINE = INNODB;

CREATE TABLE IF NOT EXISTS admin(

	id_admin INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	id_user INT NOT NULL,
	FOREIGN KEY(id_user) REFERENCES users(id_user)

)ENGINE = INNODB;

CREATE TABLE IF NOT EXISTS demande(

	id_dem INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	id_user INT NOT NULL,
	FOREIGN KEY(id_user) REFERENCES users(id_user),
	id_serv INT NOT NULL,
	FOREIGN KEY(id_serv) REFERENCES service(id_serv),
	experience VARCHAR(255) NOT NULL
)ENGINE = INNODB;

